if [ -n "$BASH_VERSION" ]; then
	# include .bashrc if it exists
	if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi

# function definitions, see ~/.bash_functions
if [ -f ~/.bash_functions ]; then
    . ~/.bash_functions
fi

# alias definitions, see ~/.bash_aliases
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# exports
export GIT_PATH=~/projects/github
export DEV_PATH=$GIT_PATH/sgoodrow
export JAVA_HOME="/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home"

# z
. ${DEV_PATH}/dotfiles/z/z.sh

# maven bash completion
. ~/.maven_bash_completion.bash

# more bash completion
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion || {
    # if not found in /usr/local/etc, try the brew --prefix location
    [ -f "$(brew --prefix)/etc/bash_completion.d/git-completion.bash" ] && \
        . $(brew --prefix)/etc/bash_completion.d/git-completion.bash
}

# prompt
DIM='\e[2m'
RESET='\e[0m'
export PS1="${DIM}\u@\W${RESET} "

# title
export PROMPT_COMMAND='echo -ne "\033];${PWD##*/}\007"; '

clear
